### ISSUE TITLE
Directory wrong

### ISSUE THREAD

**Issue by pozitp** [ReviversMC/modget-manifests#19]
Manifest included wrong
In manifest repo this included in 0.2.x, but not in 0.3.x
![image](https://user-images.githubusercontent.com/61188367/144709218-cb02ea48-2e95-4b2f-87d4-b58d9340f527.png)

**Comment by thefirethirteen** [comment]
Fixed in pr #18, but @NebelNidas could fix this manually in the v4 branch, until v4-review gets merged into v4.

**Comment by NebelNidas** [comment]
Thank you for reporting this! Should be fixed now thanks to @thefirethirteen's contribution 😉
